INSERT INTO compliance_record (company_name, compliance_score, status, description, created_at)
VALUES
('GreenGrid Manufacturing', 92, 'COMPLIANT', 'Uses renewable electricity contracts and tracks supplier emissions quarterly.', CURRENT_TIMESTAMP),
('BlueRiver Textiles', 68, 'PENDING_REVIEW', 'Water recycling program is active, but wastewater testing records are incomplete.', CURRENT_TIMESTAMP),
('SolarPeak Logistics', 81, 'COMPLIANT', 'Fleet emissions are monitored and electric vehicle adoption is underway.', CURRENT_TIMESTAMP),
('UrbanLeaf Foods', 74, 'PENDING_REVIEW', 'Packaging reduction goals exist, but supplier certification evidence needs review.', CURRENT_TIMESTAMP),
('EcoForge Steel', 55, 'NON-COMPLIANT', 'Energy intensity remains above target and remediation plan is overdue.', CURRENT_TIMESTAMP),
('ClearSky Electronics', 88, 'COMPLIANT', 'E-waste handling, conflict minerals screening, and energy reporting are documented.', CURRENT_TIMESTAMP),
('RiverStone Chemicals', 49, 'NON-COMPLIANT', 'Hazardous waste manifests and spill response drills are missing for two sites.', CURRENT_TIMESTAMP),
('NorthStar Retail', 79, 'PENDING_REVIEW', 'Store energy audits are complete, but Scope 3 reporting is still being consolidated.', CURRENT_TIMESTAMP),
('TerraNova Packaging', 95, 'COMPLIANT', 'High recycled content, ISO 14001 certification, and supplier audits are current.', CURRENT_TIMESTAMP),
('BrightPath Construction', 63, 'PENDING_REVIEW', 'Construction waste diversion is improving, but site-level evidence is inconsistent.', CURRENT_TIMESTAMP),
('OceanGate Fisheries', 44, 'NON-COMPLIANT', 'Traceability documentation is incomplete and corrective actions are pending.', CURRENT_TIMESTAMP),
('Everwood Furniture', 86, 'COMPLIANT', 'Certified timber sourcing and low-VOC finishing processes are verified.', CURRENT_TIMESTAMP),
('MetroCharge Energy', 91, 'COMPLIANT', 'Charging network runs on renewable tariffs with published carbon intensity metrics.', CURRENT_TIMESTAMP),
('PureCycle Plastics', 83, 'COMPLIANT', 'Closed-loop recycling process and material recovery rates are independently reviewed.', CURRENT_TIMESTAMP),
('AquaPure Beverages', 72, 'PENDING_REVIEW', 'Water stewardship targets are defined, but plant-level consumption variance needs analysis.', CURRENT_TIMESTAMP),
('Summit Apparel', 58, 'NON-COMPLIANT', 'Supplier labor and environmental audit gaps remain open beyond target dates.', CURRENT_TIMESTAMP),
('WindFarm Components', 89, 'COMPLIANT', 'Lifecycle assessment records and renewable sourcing controls are maintained.', CURRENT_TIMESTAMP),
('HarvestLink Agritech', 76, 'PENDING_REVIEW', 'Soil health monitoring is active, but fertilizer runoff data needs validation.', CURRENT_TIMESTAMP),
('CoreLite Cement', 47, 'NON-COMPLIANT', 'Carbon reduction roadmap is not aligned with current production emissions.', CURRENT_TIMESTAMP),
('CleanWave Shipping', 69, 'PENDING_REVIEW', 'Fuel efficiency metrics improved, but port emissions controls are incomplete.', CURRENT_TIMESTAMP),
('BioNest Labs', 94, 'COMPLIANT', 'Chemical handling, waste segregation, and energy tracking meet internal standards.', CURRENT_TIMESTAMP),
('ReNew Data Centers', 90, 'COMPLIANT', 'Power usage effectiveness and renewable procurement are reported monthly.', CURRENT_TIMESTAMP),
('SafeHarvest Grocers', 80, 'COMPLIANT', 'Food waste diversion and refrigeration leak monitoring are operating effectively.', CURRENT_TIMESTAMP),
('IronTrail Mining', 39, 'NON-COMPLIANT', 'Tailings inspection records and biodiversity restoration evidence are insufficient.', CURRENT_TIMESTAMP),
('LumaHome Appliances', 84, 'COMPLIANT', 'Product efficiency standards and take-back programs are documented.', CURRENT_TIMESTAMP),
('EcoMed Devices', 77, 'PENDING_REVIEW', 'Sterilization emissions data requires review before final compliance scoring.', CURRENT_TIMESTAMP),
('PrairieWind Farms', 87, 'COMPLIANT', 'Water, soil, and renewable energy indicators are verified for the current period.', CURRENT_TIMESTAMP),
('CityLoop Transit', 73, 'PENDING_REVIEW', 'Fleet transition plan is funded, but charging infrastructure milestones are delayed.', CURRENT_TIMESTAMP),
('StoneBridge Paper', 52, 'NON-COMPLIANT', 'Deforestation risk screening and effluent controls need corrective action.', CURRENT_TIMESTAMP),
('NexGen Batteries', 82, 'COMPLIANT', 'Battery recycling chain of custody and safety controls are audit-ready.', CURRENT_TIMESTAMP)
ON CONFLICT (company_name) DO NOTHING;
